// ----------------------------------------------------------------------

const mypage = {
  workgroup: {
    name: '일반근로제A',
    type: '일반',
    worktime: '09:00 ~ 18:00',
    breaktime: '12:00 ~ 13:00',
    coretime: '13:00 ~ 16:00',
    Approvetime: '18:00 ~ 00:00',
  },
  weeklyWorkData: [
    {
      date: '2023-08-01',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-02',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-03',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-4',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-08-5',
      workingTime: 0,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-08-6',
      workingTime: 0,
      overTime: 0,
      dayType: '유급',
    },
    {
      date: '2023-08-07',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-08',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-09',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-10',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-08-11',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-12',
      workingTime: 0,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-08-13',
      workingTime: 4,
      overTime: 0,
      dayType: '유급',
    },
    {
      date: '2023-08-14',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-15',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-16',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-17',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-08-18',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-19',
      workingTime: 0,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-08-20',
      workingTime: 4,
      overTime: 0,
      dayType: '유급',
    },
    {
      date: '2023-08-21',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-22',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-23',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-24',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-08-25',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-26',
      workingTime: 0,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-08-27',
      workingTime: 4,
      overTime: 0,
      dayType: '유급',
    },
    {
      date: '2023-08-28',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-29',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-30',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-08-31',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-09-01',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-09-02',
      workingTime: 8,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-09-03',
      workingTime: 8,
      overTime: 0,
      dayType: '유급',
    },
    {
      date: '2023-09-04',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-09-05',
      workingTime: 8,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-09-06',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-09-07',
      workingTime: 8,
      overTime: 2,
      dayType: '근무',
    },
    {
      date: '2023-09-08',
      workingTime: 7,
      overTime: 0,
      dayType: '근무',
    },
    {
      date: '2023-09-09',
      workingTime: 0,
      overTime: 0,
      dayType: '무급',
    },
    {
      date: '2023-09-10',
      workingTime: 0,
      overTime: 0,
      dayType: '유급',
    },
  ],
};

export default mypage;
